server:
  port: ${PORT:2222}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coreloka
    username: coreloka
    password: coreloka
    tomcat:
      test-while-idle: : true
      validation-query: SELECT 1
      max-active: 50
      max-wait: 10000
      test-on-borrow: true

  jpa:
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

