info:
  component: Edge Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    account:
      path: /loka/**
      serviceId: loka-service
  ignoredServices: "*"

ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 3000
  ReadTimeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    registerWithEureka: false

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG