server:
  port: 8081

spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: false
      server:
        health:
          enabled: false
        monitor:
          github:
            enabled: true
        git:
          uri: https://github.com/CarlosCedeniio/config-repo.git
#          force-pull: true
#          username: ${github.username}
#          password: ${github.password}
#  rabbitmq:
#    host: 192.168.99.100
#    port: 30000
#    username: guest
#    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true

logging:
  level:
    org.springframework.cloud.config: DEBUG

#endpoints:
#  restart:
#    enabled: false

management:
  security:
    enabled: false