## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#spring.datasource.url = jdbc:mysql://localhost:3306/test?useSSL=false
#spring.datasource.username = root
#spring.datasource.password = @root123

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

# Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = create-drop

mms:
    encryption:
        key: pacificsoft

server:
  port: ${PORT:2222}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2


# ===============================
# DATABASE
# ===============================
spring:
  main:
      allow-bean-definition-overriding: true
  datasource:
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:mysql://25.4.250.51/tracking?userSSL=false&serverTimezone=EST
    #url: jdbc:mysql://localhost/Tracking?userSSL=false&serverTimezone=UTC
    username: allan
    password: allan
    tomcat:
          test-while-idle: true
          validation-query: SELECT 1
          max-active: 50
          max-wait: 10000
          test-on-borrow: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true